#!/bin/sh
#
# Integration test (requires firefox)

set -e

cleanup() {
  kill 0 && wait
}

curl_with_retry() {
  curl --silent --retry 2 --retry-connrefused --max-time 5 "$@" > /dev/null
}

trap cleanup EXIT

# Start weblink
bin/weblink --client --server &

# Wait for weblink to be ready
curl_with_retry http://127.0.0.1:8080/

# Establish connection between the client and server
firefox "http://127.0.0.1:8080/?server=ws://127.0.0.1:8000&batch=2"

# Test that everything works
for _ in $(seq 1 3); do
  (curl_with_retry -px http://127.0.0.1:3128 https://www.google.com/ && echo "SUCCESS" || echo "FAILURE") &
  pids="$! $pids"
done
wait $pids
