#!/bin/sh
#
# Integration tests (requires firefox)

set -e

cleanup() {
  kill 0 && wait
}

trap cleanup EXIT

curl_with_retry() {
  curl --silent --retry 2 --retry-connrefused --max-time 5 --output /dev/null "$@"
}

# Start weblink
bin/weblink --client --server &
# Wait for weblink to be ready
curl_with_retry http://127.0.0.1:8080/
# Establish connection between the client and the server
firefox "http://127.0.0.1:8080/?server=ws://127.0.0.1:8000&batch=2"
# Make multiple requests in parallel through weblink to test everything
for _ in $(seq 1 3); do
  (curl_with_retry -px http://127.0.0.1:3128 https://www.google.com/ \
    && echo "SUCCESS" || echo "FAILURE") &
  pids="$! $pids"
done
# shellcheck disable=SC2086
wait $pids
